#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# ── Wizard-specific helpers ───────────────────────────────────────────────
SCRIPT_PATH="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
BACKUP_DIR="$HOME/.ghostty-herdr-wizard-backups/$(date +%Y%m%d-%H%M%S)"

# Homebrew lives in /opt/homebrew on Apple silicon and /usr/local on Intel. Put it
# on PATH for this run, so a terminal opened before installing brew still works.
BREW_BIN="$(command -v brew 2>/dev/null || true)"
for candidate in /opt/homebrew/bin/brew /usr/local/bin/brew; do
  if [[ -z "$BREW_BIN" && -x "$candidate" ]]; then BREW_BIN="$candidate"; fi
done
if [[ -n "$BREW_BIN" ]]; then eval "$("$BREW_BIN" shellenv)"; fi
BREW_PREFIX="$(brew --prefix 2>/dev/null || echo /opt/homebrew)"
GHOSTTY_BIN="/Applications/Ghostty.app/Contents/MacOS/ghostty"
HERDR_BIN="$BREW_PREFIX/bin/herdr"
LAUNCHER="$HOME/.local/bin/ghostty-launch"
CHEATSHEET="$HOME/.config/ghostty-herdr-cheatsheet.md"
STATUSLINE="$HOME/.claude/statusline.sh"
CHANGED=() # files this run created or modified

ok()  { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
cmd() { printf '  %s$ %s%s\n' "$DIM" "$*" "$RESET"; }

# run CMD...: show a command and run it. A failure is recorded for the closing
# summary instead of aborting, so one flaky install doesn't sink the rest.
run() {
  cmd "$*"
  if "$@"; then return 0; fi
  warn "failed: $*"
  SKIPPED+=("re-run manually: $*")
  return 0
}

# current_projects_dir: where the user keeps their repos. Remembered in the
# wizard's ~/.zprofile block; otherwise the first common folder that exists.
current_projects_dir() {
  local line candidate
  line=$(grep -E '^export PROJECTS_DIR=' "$HOME/.zprofile" 2>/dev/null | tail -1 || true)
  if [[ -n "$line" ]]; then
    line=${line#export PROJECTS_DIR=}
    line=${line#\"}
    line=${line%\"}
    printf '%s' "${line/\$HOME/$HOME}"
    return 0
  fi
  if [[ -n "${PROJECTS_DIR:-}" ]]; then
    printf '%s' "$PROJECTS_DIR"
    return 0
  fi
  for candidate in "$HOME/code" "$HOME/Code" "$HOME/projects" "$HOME/Projects" "$HOME/dev" "$HOME/src" "$HOME/Developer"; do
    if [[ -d "$candidate" ]]; then
      printf '%s' "$candidate"
      return 0
    fi
  done
  printf '%s' "$HOME/code"
}

in_ghostty() { [[ "${TERM_PROGRAM:-}" == "ghostty" || -n "${HERDR_ENV:-}" ]]; }

# brew_formulae NAME...: install only the formulae not already present.
brew_formulae() {
  local missing=() f
  for f in "$@"; do
    brew list --formula "$f" >/dev/null 2>&1 || missing+=("$f")
  done
  if (( ${#missing[@]} == 0 )); then
    ok "already installed: $*"
  else
    run brew install "${missing[@]}"
  fi
}

# backup PATH: copy a file or directory into this run's backup folder. Only the
# first copy per run is kept, so it always holds the pre-wizard version.
backup() {
  [[ -e "$1" ]] || return 0
  local name
  name=$(printf '%s' "${1#"$HOME"/}" | tr '/' '_')
  [[ -e "$BACKUP_DIR/$name" ]] && return 0
  mkdir -p "$BACKUP_DIR"
  cp -R "$1" "$BACKUP_DIR/$name"
  note "backed up $1 → $BACKUP_DIR/$name"
}

# install_file DEST < content: write DEST if it differs. An existing file that
# differs is shown as a diff and only replaced after confirmation, with a backup.
install_file() {
  local dest="$1" tmp
  tmp=$(mktemp)
  cat > "$tmp"
  if [[ -f "$dest" ]] && cmp -s "$tmp" "$dest"; then
    rm -f "$tmp"
    ok "unchanged: $dest"
    return 0
  fi
  if [[ -f "$dest" ]]; then
    warn "$dest already exists and differs:"
    diff -u "$dest" "$tmp" | head -40 | sed 's/^/    /' || true
    # content arrived on stdin, so the prompt must read the keyboard directly
    if ! confirm "Replace it? (a backup is kept)" < /dev/tty; then
      rm -f "$tmp"
      SKIPPED+=("left $dest unchanged")
      return 0
    fi
    backup "$dest"
  fi
  mkdir -p "$(dirname "$dest")"
  mv "$tmp" "$dest"
  CHANGED+=("$dest")
  ok "wrote $dest"
}

# upsert_block FILE [COMMENT] < content: replace (or append) the wizard-managed
# block in a config file, leaving everything outside the markers untouched.
# COMMENT is the file's comment leader: "#" (default) or "--" for Lua.
upsert_block() {
  local file="$1" leader="${2:-#}" body tmp begin end
  begin="$leader >>> ghostty-herdr-wizard >>>"
  end="$leader <<< ghostty-herdr-wizard <<<"
  body=$(cat)
  tmp=$(mktemp)
  touch "$file"
  {
    awk -v b="$begin" -v e="$end" '$0==b{skip=1;next} $0==e{skip=0;next} !skip' "$file"
    printf '%s\n%s\n%s\n' "$begin" "$body" "$end"
  } > "$tmp"
  install_file "$file" < "$tmp"
  rm -f "$tmp"
}

# git_set KEY VALUE: set a global git config value if it isn't already.
git_set() {
  local current
  current=$(git config --global --get "$1" || true)
  if [[ "$current" == "$2" ]]; then
    ok "git $1 = $2"
  else
    run git config --global "$1" "$2"
  fi
}

# ctrl_space_taken: true while macOS still claims Ctrl-Space for input sources.
ctrl_space_taken() {
  local v
  v=$(/usr/libexec/PlistBuddy -c "Print :AppleSymbolicHotKeys:60:enabled" \
    "$HOME/Library/Preferences/com.apple.symbolichotkeys.plist" 2>/dev/null || echo missing)
  [[ "$v" != "false" ]]
}

# herdr_integration_current AGENT: true when herdr's hook for AGENT is up to date.
herdr_integration_current() {
  herdr integration status 2>/dev/null | grep "^$1: current" >/dev/null
}

# ghostty_config [autostart]: the full Ghostty config. "autostart" makes every
# new window go through ghostty-launch, which decides between herdr and a shell.
ghostty_config() {
  cat <<'EOF'
# Ghostty config, written by ghostty-herdr-wizard.sh
# Reference: https://ghostty.org/docs/config/reference
# Reload after editing: Cmd-Shift-,

# ── Font ──────────────────────────────────────────────
font-family = JetBrainsMono Nerd Font
font-size = 14

# ── Look ──────────────────────────────────────────────
# Follows macOS light/dark mode, same palette as herdr, nvim, bat and yazi.
theme = light:Catppuccin Latte,dark:Catppuccin Mocha
window-padding-x = 10
window-padding-y = 8
window-padding-balance = true
macos-titlebar-style = transparent
cursor-style-blink = false
mouse-hide-while-typing = true

# ── Behaviour ─────────────────────────────────────────
# Left Option acts as Alt (Alt shortcuts in herdr, nvim, fzf Alt-C).
# Right Option still types special characters.
macos-option-as-alt = left
copy-on-select = clipboard
# herdr keeps sessions alive, so closing a window never loses work.
confirm-close-surface = false
desktop-notifications = true
shell-integration-features = ssh-terminfo,ssh-env
auto-update = check

# ── Quick terminal: Ctrl-` from any app ───────────────
quick-terminal-position = top
quick-terminal-autohide = true
keybind = global:ctrl+backquote=toggle_quick_terminal

# ── herdr shortcuts ───────────────────────────────────
# Each sends herdr's prefix (Ctrl-Space is byte \x00) and then a herdr key,
# so they only do something inside herdr.
keybind = cmd+d=text:\x00v
keybind = cmd+shift+d=text:\x00-
keybind = cmd+t=text:\x00c
keybind = cmd+p=text:\x00g
keybind = cmd+o=text:\x00m
keybind = cmd+e=text:\x00f
keybind = cmd+shift+g=text:\x00d
keybind = cmd+shift+enter=text:\x00z
# Both spellings of [ and ]: Ghostty's own cmd+shift+[ / ] switch Ghostty tabs.
keybind = cmd+shift+bracket_left=text:\x00,
keybind = cmd+shift+bracket_right=text:\x00.
keybind = cmd+shift+[=text:\x00,
keybind = cmd+shift+]=text:\x00.
# digit_N is the physical key. Ghostty's built-in cmd+digit_N=goto_tab wins over
# a plain cmd+N binding, so herdr tab switching has to use the same key name.
keybind = cmd+digit_1=text:\x001
keybind = cmd+digit_2=text:\x002
keybind = cmd+digit_3=text:\x003
keybind = cmd+digit_4=text:\x004
keybind = cmd+digit_5=text:\x005
keybind = cmd+digit_6=text:\x006
keybind = cmd+digit_7=text:\x007
keybind = cmd+digit_8=text:\x008
keybind = cmd+digit_9=text:\x009
EOF
  if [[ "${1:-}" == "autostart" ]]; then
    cat <<EOF

# ── herdr in every new window ─────────────────────────
# ghostty-launch attaches herdr unless herdr is already open in another window,
# in which case you get a plain shell (so Cmd-N is the "no herdr" shortcut).
# Delete this line to go back to plain shells everywhere.
command = direct:$LAUNCHER
EOF
  fi
}

install_launcher() {
  install_file "$LAUNCHER" <<'EOF'
#!/bin/zsh
# ghostty-launch: Ghostty runs this for every new window, tab and the quick terminal.
# Written by ghostty-herdr-wizard.sh.
#
#   herdr not open in any window    → attach herdr (opening Ghostty lands you in herdr)
#   herdr already open elsewhere    → plain shell (Cmd-N is the "without herdr" shortcut)
#   you detach herdr (Ctrl-Space q) → this window carries on as a plain shell
#   GHOSTTY_NO_HERDR=1 is set       → always a plain shell
# Ghostty starts this with macOS's minimal PATH. herdr needs Homebrew's, e.g. to
# find terminal-notifier for desktop notifications.
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:$PATH"

herdr_bin=""
for candidate in /opt/homebrew/bin/herdr /usr/local/bin/herdr "$HOME/.local/bin/herdr"; do
  if [[ -x "$candidate" ]]; then herdr_bin="$candidate"; break; fi
done

# A herdr client's command line is just ".../herdr"; the background server is "herdr server".
if [[ -n "$herdr_bin" && -z "${GHOSTTY_NO_HERDR:-}" ]] && ! pgrep -f '(^|/)herdr$' >/dev/null 2>&1; then
  "$herdr_bin"
fi
exec "${SHELL:-/bin/zsh}" -l
EOF
  chmod +x "$LAUNCHER"
}

# write_ghostty_config: the Ghostty config, with herdr auto-start once herdr exists.
write_ghostty_config() {
  if [[ -x "$HERDR_BIN" ]]; then
    install_launcher
    install_file "$HOME/.config/ghostty/config" < <(ghostty_config autostart)
  else
    install_file "$HOME/.config/ghostty/config" < <(ghostty_config)
  fi
  if "$GHOSTTY_BIN" +validate-config; then
    ok "Ghostty config is valid"
  else
    warn "Ghostty reported config problems (above)"
    SKIPPED+=("fix Ghostty config errors: $GHOSTTY_BIN +validate-config")
  fi
}

# starship_config: the pastel-powerline preset with the Apple logo in place of
# the username, plus Deno and Python versions next to Node and Bun.
#
# The preset only sets backgrounds, so text takes the terminal's default colour
# and is hard to read in both light and dark mode. Each segment gets a fixed
# text colour instead, with its background shifted until contrast is at least
# 5:1 (WCAG AA is 4.5): white on darker shades, #1E1E2E on lighter ones.
starship_config() {
  local apple=$'\xef\x85\xb9'
  starship preset pastel-powerline | awk -v apple="$apple" '
    $0 == "$username\\" { next }
    $0 == "$bun\\" { print; print "$deno\\"; print "$python\\"; next }
    /^\[os\]$/ { in_os = 1 }
    in_os && /^disabled = true/ {
      print "disabled = false"
      print "format = \"[$symbol ]($style)\""
      print ""
      print "[os.symbols]"
      print "Macos = \"" apple "\""
      in_os = 0
      next
    }
    { print }
    END {
      print ""
      print "[deno]"
      print "style = \"bg:#86BBD8\""
      print "format = \x27[ $symbol ($version) ]($style)\x27"
      print ""
      print "[python]"
      print "style = \"bg:#86BBD8\""
      print "format = \x27[ $symbol ($version) ]($style)\x27"
    }' | sed -E \
      -e 's/#DA627D/#B8476B/g; s/#FCA17D/#FDB598/g; s/#86BBD8/#A3CBE1/g; s/#06969A/#057C7F/g' \
      -e 's/^style = "bg:(#9A348E|#B8476B|#057C7F|#33658A)"/style = "fg:#FFFFFF bg:\1"/' \
      -e 's/^style = "bg:(#FDB598|#A3CBE1)"/style = "fg:#1E1E2E bg:\1"/' \
      -e 's/^(style_(user|root)) = "bg:#9A348E"/\1 = "fg:#FFFFFF bg:#9A348E"/'
}

statusline_script() {
  cat <<'EOF'
#!/bin/bash
# Claude Code status line, written by ghostty-herdr-wizard.sh
# Docs: https://code.claude.com/docs/en/statusline
#
# Line 1: model · effort │ directory │ worktree (only inside a linked git worktree)
# Line 2: context used │ session cost │ 5-hour limit │ weekly limit (limits: Pro/Max only)

input=$(cat)

# One jq call. Fields are joined with the ASCII unit separator, not tabs:
# `read` merges consecutive tabs, which would shift fields left when one is empty.
IFS=$'\x1f' read -r model dir worktree cost ctx_pct ctx_tokens ctx_size effort \
  five_pct five_reset week_pct <<<"$(jq -r '[
    .model.display_name // "Claude",
    .workspace.current_dir // .cwd // "",
    .workspace.git_worktree // "",
    .cost.total_cost_usd // 0,
    .context_window.used_percentage // "",
    .context_window.total_input_tokens // 0,
    .context_window.context_window_size // 0,
    .effort.level // "",
    .rate_limits.five_hour.used_percentage // "",
    .rate_limits.five_hour.resets_at // "",
    .rate_limits.seven_day.used_percentage // ""
  ] | map(tostring) | join("\u001f")' <<<"$input")"

# Catppuccin Mocha
rgb()   { printf '\033[38;2;%sm' "$1"; }
MAUVE=$(rgb "203;166;247"); BLUE=$(rgb "137;180;250"); TEAL=$(rgb "148;226;213")
GREEN=$(rgb "166;227;161"); YELLOW=$(rgb "249;226;175"); RED=$(rgb "243;139;168")
PEACH=$(rgb "250;179;135"); DIM=$(rgb "127;132;156"); RESET=$'\033[0m'
SEP=" ${DIM}│${RESET} "

ICON_MODEL=$'\xf3\xb0\x9a\xa9'  # nf-md-robot
ICON_DIR=$'\xef\x81\xbb'        # nf-fa-folder
ICON_BRANCH=$'\xee\x9c\xa5'     # nf-dev-git_branch

# pct_color N: green under 50, yellow under 80, red from 80
pct_color() {
  local p=${1%.*}
  if (( p >= 80 )); then printf '%s' "$RED"
  elif (( p >= 50 )); then printf '%s' "$YELLOW"
  else printf '%s' "$GREEN"; fi
}

# pct LABEL VALUE [SUFFIX]: "label 23%" with the number coloured by severity
pct() {
  local rounded
  rounded=$(printf '%.0f' "$2")
  printf '%s%s%s %s%s%%%s%s' "$DIM" "$1" "$RESET" "$(pct_color "$rounded")" "$rounded" "$RESET" "${3:-}"
}

# tokens N: 950 → 950, 46500 → 47k, 1200000 → 1.2M
tokens() {
  awk -v n="$1" 'BEGIN { if (n >= 1000000) printf "%.1fM", n / 1000000; else if (n >= 1000) printf "%.0fk", n / 1000; else printf "%d", n }'
}

# Directory: ~ for home, then only the last three segments
if [[ "$dir" == "$HOME"* ]]; then dir="~${dir#"$HOME"}"; fi
dir=$(awk -F/ '{ if (NF > 4) printf "…/%s/%s/%s", $(NF-2), $(NF-1), $NF; else printf "%s", $0 }' <<<"$dir")

line1="${MAUVE}${ICON_MODEL} ${model}${RESET}"
if [[ -n "$effort" ]]; then line1+=" ${DIM}effort${RESET} ${PEACH}${effort}${RESET}"; fi
line1+="${SEP}${BLUE}${ICON_DIR} ${dir}${RESET}"
if [[ -n "$worktree" ]]; then line1+="${SEP}${TEAL}${ICON_BRANCH} worktree ${worktree}${RESET}"; fi

if [[ -n "$ctx_pct" ]]; then
  line2="$(pct context "$ctx_pct") ${DIM}($(tokens "$ctx_tokens")/$(tokens "$ctx_size") tokens)${RESET}"
else
  line2="${DIM}context –${RESET}"
fi
line2+="${SEP}${GREEN}$(printf '$%.2f' "$cost")${RESET} ${DIM}session${RESET}"
if [[ -n "$five_pct" ]]; then
  reset_note=""
  if [[ -n "$five_reset" ]]; then reset_note=" ${DIM}resets $(date -r "$five_reset" +%H:%M)${RESET}"; fi
  line2+="${SEP}$(pct "5h limit" "$five_pct" "$reset_note")"
fi
if [[ -n "$week_pct" ]]; then line2+="${SEP}$(pct "week limit" "$week_pct")"; fi

printf '%s\n%s\n' "$line1" "$line2"
EOF
}

statusline_configured() {
  [[ -f "$HOME/.claude/settings.json" ]] &&
    jq -e --arg cmd "$STATUSLINE" '.statusLine.command == $cmd' "$HOME/.claude/settings.json" >/dev/null 2>&1
}

# ── Stages ────────────────────────────────────────────────────────────────

stage_preflight() {
  say "Checks the basics. Nothing is changed here."
  say "Every later file change shows a diff first and keeps a backup in:"
  note "$BACKUP_DIR"
  printf '\n'
  if [[ "$(uname -s)" != "Darwin" ]]; then
    warn "This wizard targets macOS (Ghostty, Homebrew casks, macOS settings)."
    exit 1
  fi
  if ! command -v brew >/dev/null 2>&1; then
    warn "Homebrew not found. Install it from https://brew.sh and re-run."
    exit 1
  fi
  ok "Homebrew: $(brew --version | head -1)"
  ok "git: $(git --version)"
  if xcode-select -p >/dev/null 2>&1; then
    ok "Xcode command line tools present (Neovim needs a C compiler for syntax parsers)"
  else
    warn "Xcode command line tools missing. A macOS dialog will open."
    run xcode-select --install
    pause "Finish the install in that dialog, then press Enter"
  fi
  ok "macOS $(sw_vers -productVersion)"
  note "Tip: don't press Cmd-D / Cmd-T while the wizard runs. They send herdr commands."
  pause
}

stage_install_ghostty() {
  say "Ghostty is the terminal app. The Nerd Font adds file, git and language icons."
  if [[ -d /Applications/Ghostty.app ]]; then
    ok "Ghostty already in /Applications"
  else
    run brew install --cask ghostty
  fi
  if compgen -G "$HOME/Library/Fonts/JetBrainsMonoNerdFont*" >/dev/null; then
    ok "JetBrains Mono Nerd Font already installed"
  else
    run brew install --cask font-jetbrains-mono-nerd-font
  fi
  pause
}

stage_ghostty_config() {
  say "Font, Catppuccin theme (follows macOS light/dark), Option-as-Alt, quick terminal,"
  say "and Cmd shortcuts that drive herdr."
  write_ghostty_config
  if "$GHOSTTY_BIN" +list-fonts 2>/dev/null | grep "JetBrainsMono Nerd Font" >/dev/null; then
    ok "Ghostty can see JetBrainsMono Nerd Font"
  else
    warn "Ghostty doesn't list 'JetBrainsMono Nerd Font' yet. It may appear after Ghostty restarts."
  fi
  if "$GHOSTTY_BIN" +list-themes 2>/dev/null | grep "Catppuccin Mocha" >/dev/null; then
    ok "Catppuccin themes found"
  else
    warn "Couldn't confirm the 'Catppuccin Mocha' theme name. Check with: ghostty +list-themes"
  fi
  pause
}

stage_move_into_ghostty() {
  if ! in_ghostty; then
    say "The rest of the setup needs to run inside Ghostty so you can check how it looks."
    open -a Ghostty || warn "couldn't open Ghostty; open it from /Applications"
    printf 'bash %q --from 4' "$SCRIPT_PATH" | pbcopy
    step "If macOS asks whether to open Ghostty, click Open."
    step "In the Ghostty window, press Cmd-V then Enter (the re-run command is on your clipboard):"
    note "bash $SCRIPT_PATH --from 4"
    printf '\n'
    note "This window's part is done. You can close it."
    exit 0
  fi
  ok "Running inside Ghostty"
  say "Check the icons below. You should see: React, TypeScript, git branch, folder, Node, Apple."
  printf '\n      %s    %s    %s    %s    %s    %s\n\n' \
    $'\xee\x9e\xba' $'\xee\x98\xa8' $'\xee\x9c\xa5' $'\xef\x81\xbb' $'\xee\x9c\x98' $'\xef\x85\xb9'
  step "Also check: text uses JetBrains Mono, and colours are Catppuccin (dark mauve/pink tones)."
  if ! confirm "Do all six icons render (no boxes or question marks)?"; then
    warn "Quit Ghostty fully (Cmd-Q), reopen it, and re-run. Fonts load at app start."
    SKIPPED+=("Nerd Font icons not rendering: restart Ghostty and check 'ghostty +list-fonts'")
  fi
}

stage_free_ctrl_space() {
  say "herdr's prefix is Ctrl-Space. macOS uses that key to switch keyboard input"
  say "source by default, which would swallow it."
  if ctrl_space_taken; then
    open_url "x-apple.systempreferences:com.apple.Keyboard-Settings.extension"
    step "Click 'Keyboard Shortcuts…'."
    step "Pick 'Input Sources' in the left list."
    step "Untick 'Select the previous input source' (^Space)."
    step "Untick 'Select next source in Input menu' (^⌥Space) too."
    step "Click Done."
    pause "Press Enter when done"
    if ctrl_space_taken; then
      warn "macOS still reports Ctrl-Space as taken. If you only have one input source it may not matter."
      SKIPPED+=("confirm Ctrl-Space is free: System Settings → Keyboard → Keyboard Shortcuts → Input Sources")
    else
      ok "Ctrl-Space is free"
    fi
  else
    ok "Ctrl-Space is already free"
  fi
  pause
}

stage_toolbelt() {
  say "bat (cat with syntax), eza (ls with icons/git), fd + ripgrep (find/grep), fzf (fuzzy"
  say "finder), zoxide (jump dirs), glow (markdown), jless (JSON viewer), btop (processes),"
  say "tlrc (tldr examples), zsh autosuggestions + syntax highlighting."
  brew_formulae bat eza fd ripgrep fzf zoxide starship glow jless btop tlrc jq \
    zsh-autosuggestions zsh-syntax-highlighting
  say "Catppuccin themes for bat (delta reuses them):"
  local bat_themes flavour
  bat_themes="$(bat --config-dir)/themes"
  mkdir -p "$bat_themes"
  for flavour in Mocha Latte; do
    if [[ -f "$bat_themes/Catppuccin $flavour.tmTheme" ]]; then
      ok "bat theme Catppuccin $flavour present"
    else
      run curl -fsSL -o "$bat_themes/Catppuccin $flavour.tmTheme" \
        "https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20$flavour.tmTheme"
    fi
  done
  run bat cache --build
  pause
}

stage_starship() {
  say "Pastel powerline prompt:   Apple  ›  folder  ›  git branch  ›  Node/Bun/Deno/Python version  ›  time"
  note "Runtime versions only appear inside projects that use them (e.g. a package.json for Node)."
  brew_formulae starship
  local preset
  if preset=$(starship_config) && [[ -n "$preset" ]]; then
    install_file "$HOME/.config/starship.toml" <<<"$preset"
    printf '\n'
    say "Preview (in this directory):"
    printf '  '
    STARSHIP_SHELL=bash starship prompt 2>/dev/null | tail -1 | sed 's/\\\[//g; s/\\\]//g' || true
    printf '%s\n\n' "$RESET"
    note "New shells use it. Tweak segments in ~/.config/starship.toml (https://starship.rs/config)."
  else
    warn "couldn't generate the pastel-powerline preset; the default prompt still works"
    SKIPPED+=("starship preset: starship preset pastel-powerline -o ~/.config/starship.toml")
  fi
  pause
}

stage_shell() {
  say "Adds a marked block to ~/.zprofile and ~/.zshrc. Your existing lines stay as they are."
  note "Aliases like ls→eza and cat→bat are skipped inside Claude Code's shell, so agents"
  note "get the real commands and their flags."
  printf '\n'
  local projects answer projects_line
  projects=$(current_projects_dir)
  say "Where do you keep your git repos? 'p' and herdr's prefix m search this folder."
  printf '  %sProjects folder%s %s[Enter keeps %s]%s ' "$BOLD" "$RESET" "$DIM" "$projects" "$RESET"
  read -r answer || true
  if [[ -n "$answer" ]]; then projects="${answer/#\~/$HOME}"; fi
  if [[ ! -d "$projects" ]]; then
    if confirm "$projects doesn't exist. Create it?"; then
      mkdir -p "$projects"
    else
      warn "p and prefix m will find nothing until $projects exists"
    fi
  fi
  if [[ "$projects" == "$HOME"/* ]]; then
    projects_line="\$HOME${projects#"$HOME"}"
  else
    projects_line="$projects"
  fi
  export PROJECTS_DIR="$projects"
  printf '\n'
  upsert_block "$HOME/.zprofile" < <(
    cat <<'EOF'
export PATH="$HOME/.local/bin:$PATH"
export EDITOR=nvim VISUAL=nvim
EOF
    printf 'export PROJECTS_DIR="%s"\n' "$projects_line"
    cat <<'EOF'
export BAT_THEME_DARK="Catppuccin Mocha" BAT_THEME_LIGHT="Catppuccin Latte"
EOF
  )
  upsert_block "$HOME/.zshrc" <<'EOF'
# Ghostty shell integration for plain shells. Ghostty starts windows through
# ghostty-launch, so it can't inject this itself. Skipped inside herdr panes.
if [[ -n "${GHOSTTY_RESOURCES_DIR:-}" && -z "${HERDR_ENV:-}" ]]; then
  builtin source "$GHOSTTY_RESOURCES_DIR/shell-integration/zsh/ghostty-integration"
fi

HISTFILE=~/.zsh_history HISTSIZE=50000 SAVEHIST=50000
setopt share_history hist_ignore_all_dups

(( $+commands[starship] )) && eval "$(starship init zsh)"
(( $+commands[zoxide] )) && eval "$(zoxide init zsh)"
if (( $+commands[fzf] )); then
  source <(fzf --zsh)   # Ctrl-R history, Ctrl-T files, Alt-C cd
  export FZF_DEFAULT_COMMAND='fd --hidden --exclude .git'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_CTRL_T_OPTS="--preview 'bat --color=always --style=numbers --line-range=:300 {}'"
  export FZF_ALT_C_COMMAND='fd --type d --hidden --exclude .git'
fi

# Human-friendly replacements. Claude Code (CLAUDECODE=1) snapshots aliases into
# its own shell, where eza/bat would break flags like `ls -lt` or `cat -v`.
if [[ -z "${CLAUDECODE:-}" ]]; then
  alias ls='eza --icons=auto --group-directories-first'
  alias ll='eza -la --icons=auto --group-directories-first --git'
  alias lt='eza --tree --level=2 --icons=auto --git-ignore'
  alias cat='bat --paging=never'
fi
alias v='nvim'
alias lg='lazygit'
alias gd='git diff'
alias gds='DELTA_FEATURES=+side-by-side git diff'
alias keys='glow -p ~/.config/ghostty-herdr-cheatsheet.md'

# p: fuzzy-jump into a project directory
p() { local d; d=$(hproj --print) && [[ -n "$d" ]] && cd "$d"; }

# y: browse files with yazi; the shell follows you into the last directory
y() {
  local tmp cwd
  tmp="$(mktemp -t yazi-cwd.XXXXXX)"
  yazi "$@" --cwd-file="$tmp"
  IFS= read -r -d '' cwd < "$tmp"
  [[ -n "$cwd" && "$cwd" != "$PWD" ]] && builtin cd -- "$cwd"
  rm -f -- "$tmp"
}

_brew="${HOMEBREW_PREFIX:-/opt/homebrew}/share"
[[ -r $_brew/zsh-autosuggestions/zsh-autosuggestions.zsh ]] && source $_brew/zsh-autosuggestions/zsh-autosuggestions.zsh
# syntax highlighting must load last
[[ -r $_brew/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] && source $_brew/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
unset _brew
EOF
  install_file "$HOME/.local/bin/hproj" <<'EOF'
#!/usr/bin/env bash
# hproj: fuzzy-pick a project and open it as a herdr workspace.
#   hproj          create and focus a herdr workspace for the project
#   hproj --print  only print the chosen path (used by the `p` shell function)
set -euo pipefail
export PATH="/opt/homebrew/bin:/usr/local/bin:$HOME/.local/bin:$PATH"
root="${PROJECTS_DIR:-$HOME/code}"
choice=$(
  {
    fd --type d --max-depth 1 . "$root"
    fd --hidden --no-ignore --type d --max-depth 4 --exclude node_modules '^\.git$' "$root" --exec dirname {}
  } | sed -e 's:/*$::' -e "s:^$root/::" | sort -u |
    fzf --prompt='project › ' --preview "eza --tree --level=2 --icons=always --color=always --git-ignore '$root'/{}"
) || exit 0
dir="$root/$choice"
if [[ "${1:-}" == "--print" ]]; then
  printf '%s\n' "$dir"
else
  herdr workspace create --cwd "$dir" --label "$(basename "$dir")" --focus >/dev/null
fi
EOF
  chmod +x "$HOME/.local/bin/hproj"
  install_file "$CHEATSHEET" < <(cheatsheet)
  note "New shells pick this up. This wizard's own shell doesn't need it."
  pause
}

stage_git_diffs() {
  say "delta: every git diff/log/show gets syntax highlighting, line numbers, n/N to jump files."
  say "difftastic: structural diffs that ignore formatting noise (git dft, git dlog)."
  brew_formulae git-delta difftastic
  say "These global git settings will be applied:"
  note "core.pager=delta  interactive.diffFilter='delta --color-only'"
  note "delta.navigate=true  delta.line-numbers=true"
  note "merge.conflictStyle=zdiff3  diff.colorMoved=default  diff.algorithm=histogram"
  note "alias.dft / alias.dlog / alias.dshow (difftastic)"
  note "init.defaultBranch=main  push.autoSetupRemote=true"
  if confirm "Apply them? (~/.gitconfig is backed up first)"; then
    backup "$HOME/.gitconfig"
    git_set core.pager delta
    git_set interactive.diffFilter "delta --color-only"
    git_set delta.navigate true
    git_set delta.line-numbers true
    git_set merge.conflictStyle zdiff3
    git_set diff.colorMoved default
    git_set diff.algorithm histogram
    git_set alias.dft "-c diff.external=difft diff"
    git_set alias.dlog "-c diff.external=difft log -p --ext-diff"
    git_set alias.dshow "-c diff.external=difft show --ext-diff"
    git_set init.defaultBranch main
    git_set push.autoSetupRemote true
  else
    SKIPPED+=("git delta/difftastic settings not applied")
  fi
  pause
}

stage_lazygit() {
  say "A full git UI: stage single lines or hunks, commit, rebase, resolve conflicts."
  say "Diffs render through delta; press | inside lazygit to switch to difftastic."
  brew_formulae lazygit
  local lg_dir
  if lg_dir=$(lazygit --print-config-dir 2>/dev/null) && [[ -n "$lg_dir" ]]; then
    install_file "$lg_dir/config.yml" <<'EOF'
# lazygit config, written by ghostty-herdr-wizard.sh
# Reference: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  nerdFontsVersion: "3"
git:
  # press | to cycle between these
  diffRenderers:
    - type: stdinFilter
      name: delta
      command: delta --paging=never
    - type: extDiff
      name: difftastic
      command: difft --color=always
os:
  editPreset: nvim
EOF
  else
    warn "couldn't find lazygit's config directory"
    SKIPPED+=("lazygit config not written")
  fi
  pause
}

stage_github() {
  say "gh-dash lists your PRs, review requests and issues in the terminal. Opens with"
  say "herdr prefix then i. Press d on a PR to see its diff, c to comment."
  brew_formulae gh
  if gh auth status >/dev/null 2>&1; then
    ok "gh is already logged in"
  else
    say "gh will print a one-time code and open github.com in your browser."
    step "Copy the code, press Enter, paste it on the GitHub page, click Authorize."
    step "If asked 'Authenticate Git with your GitHub credentials?': Yes lets git push over HTTPS"
    step "through gh. Answer No if you already use SSH keys or another credential helper."
    pause "Press Enter to start the login"
    run gh auth login --hostname github.com --git-protocol https --web
  fi
  if gh extension list 2>/dev/null | grep 'gh-dash' >/dev/null; then
    ok "gh-dash already installed"
  else
    run gh extension install dlvhdr/gh-dash
  fi
  pause
}

stage_neovim() {
  say "LazyVim with TypeScript, Tailwind, ESLint, Prettier, JSON and Markdown support,"
  say "tuned for working next to agents: auto-reload of changed files and Diffview for review."
  note "Other languages (Python, Go, Rust, …): run :LazyExtras inside Neovim and press x to enable."
  brew_formulae neovim tree-sitter-cli
  local nvim_dir="$HOME/.config/nvim" fresh=false
  local lazy_lua="$nvim_dir/lua/config/lazy.lua"
  if [[ -f "$lazy_lua" ]] && grep -q 'LazyVim/LazyVim' "$lazy_lua"; then
    ok "LazyVim config already present"
  else
    if [[ -e "$nvim_dir" ]]; then
      warn "$nvim_dir exists but isn't LazyVim."
      if confirm "Move it to the backup folder and install LazyVim?"; then
        mkdir -p "$BACKUP_DIR"
        run mv "$nvim_dir" "$BACKUP_DIR/nvim"
      fi
    fi
    if [[ ! -e "$nvim_dir" ]]; then
      run git clone --depth 1 https://github.com/LazyVim/starter "$nvim_dir"
      rm -rf "$nvim_dir/.git"
      fresh=true
    fi
  fi
  if [[ ! -f "$lazy_lua" ]]; then
    SKIPPED+=("LazyVim not installed")
    pause
    return 0
  fi

  local extras='    { import = "lazyvim.plugins.extras.lang.typescript" },
    { import = "lazyvim.plugins.extras.lang.tailwind" },
    { import = "lazyvim.plugins.extras.lang.json" },
    { import = "lazyvim.plugins.extras.lang.markdown" },
    { import = "lazyvim.plugins.extras.linting.eslint" },
    { import = "lazyvim.plugins.extras.formatting.prettier" },'
  if grep -q 'extras.lang.typescript' "$lazy_lua"; then
    ok "language extras already enabled"
  else
    EXTRAS="$extras" awk '{print} /import = "lazyvim.plugins" }/ && !done {print ENVIRON["EXTRAS"]; done=1}' \
      "$lazy_lua" > "$lazy_lua.new"
    if grep -q 'extras.lang.typescript' "$lazy_lua.new"; then
      install_file "$lazy_lua" < "$lazy_lua.new"
    else
      warn "couldn't find where to add extras in lazy.lua; add them later with :LazyExtras"
      SKIPPED+=("enable LazyVim extras with :LazyExtras (typescript, tailwind, eslint, prettier)")
    fi
    rm -f "$lazy_lua.new"
  fi

  install_file "$nvim_dir/lua/plugins/colorscheme.lua" <<'EOF'
-- Catppuccin; the flavour follows the terminal's light/dark background.
return {
  { "LazyVim/LazyVim", opts = { colorscheme = "catppuccin" } },
}
EOF
  install_file "$nvim_dir/lua/plugins/diffview.lua" <<'EOF'
-- Review everything an agent changed: file list on the left, before/after on the right.
return {
  {
    "sindrets/diffview.nvim",
    cmd = { "DiffviewOpen", "DiffviewClose", "DiffviewFileHistory" },
    keys = {
      { "<leader>gv", "<cmd>DiffviewOpen<cr>", desc = "Review changes (Diffview)" },
      { "<leader>gV", "<cmd>DiffviewClose<cr>", desc = "Close Diffview" },
      { "<leader>gH", "<cmd>DiffviewFileHistory %<cr>", desc = "File history (Diffview)" },
    },
  },
}
EOF
  upsert_block "$nvim_dir/lua/config/autocmds.lua" "--" <<'EOF'
-- Reload files that an agent changed on disk. LazyVim only checks when the
-- terminal regains focus, which doesn't happen when you switch herdr panes.
vim.o.autoread = true
local agent_reload = vim.uv.new_timer()
agent_reload:start(1000, 1000, vim.schedule_wrap(function()
  if vim.fn.mode() == "n" and vim.fn.getcmdwintype() == "" then
    vim.cmd("silent! checktime")
  end
end))
vim.api.nvim_create_autocmd({ "BufEnter", "CursorHold" }, {
  group = vim.api.nvim_create_augroup("agent_reload", { clear = true }),
  command = "silent! checktime",
})
EOF

  say "Downloading plugins (takes a minute or two)..."
  run nvim --headless "+Lazy! sync" +qa
  if $fresh; then
    printf '\n'
    step "Open a new Ghostty window (Cmd-N), run  p  to jump into one of your repos, then  nvim"
    step "Wait while Mason installs language servers (progress shows bottom right)."
    step "Press Space and pause: a menu of every command appears."
    step "Try Space Space (find file), Space / (search text), then gd on a symbol (go to definition)."
    step "Quit with :qa"
    pause "Press Enter when Neovim opened cleanly"
  else
    pause
  fi
}

stage_yazi() {
  say "Three-column file browser with code, image and PDF previews."
  say "Opens with herdr prefix then f, or y in any shell."
  brew_formulae yazi poppler resvg
  local flavors_ok=true flavour
  for flavour in catppuccin-mocha catppuccin-latte; do
    if [[ -d "$HOME/.config/yazi/flavors/$flavour.yazi" ]]; then
      ok "yazi flavour $flavour present"
    else
      cmd "ya pkg add yazi-rs/flavors:$flavour"
      if ! ya pkg add "yazi-rs/flavors:$flavour"; then
        flavors_ok=false
        warn "couldn't install yazi flavour $flavour"
      fi
    fi
  done
  if $flavors_ok; then
    install_file "$HOME/.config/yazi/theme.toml" <<'EOF'
[flavor]
dark = "catppuccin-mocha"
light = "catppuccin-latte"
EOF
  else
    SKIPPED+=("yazi Catppuccin flavours: ya pkg add yazi-rs/flavors:catppuccin-mocha")
  fi
  pause
}

stage_herdr() {
  say "herdr runs your terminals in a background server: one workspace per repo, tabs"
  say "and panes inside, and a sidebar showing which agents are working, idle or"
  say "waiting for you. Closing Ghostty never stops them."
  note "terminal-notifier delivers herdr's desktop notifications (see the notifications stage)."
  brew_formulae herdr terminal-notifier
  install_file "$HOME/.config/herdr/config.toml" <<'EOF'
# herdr config, written by ghostty-herdr-wizard.sh
# Reference: https://herdr.dev/docs/configuration/
# Apply changes: prefix Shift-R (or: herdr server reload-config)
onboarding = false

[terminal]
# login shells so popups and panes get Homebrew's PATH
shell_mode = "login"
new_cwd = "follow"

[theme]
name = "catppuccin"
auto_switch = true
dark_name = "catppuccin"
light_name = "catppuccin-latte"

[keys]
# Claude Code keeps Ctrl-B for backgrounding commands.
prefix = "ctrl+space"
next_agent = "prefix+a"
previous_agent = "prefix+shift+a"
previous_workspace = "prefix+comma"
next_workspace = "prefix+period"
last_pane = "prefix+space"

[[keys.command]]
key = "prefix+m"
type = "popup"
command = "zsh -lc 'exec hproj'"
description = "open a project as a workspace"
width = "70%"
height = "70%"

[[keys.command]]
key = "prefix+d"
type = "popup"
command = "zsh -lc 'exec lazygit'"
description = "lazygit"
width = "92%"
height = "92%"

[[keys.command]]
key = "prefix+f"
type = "popup"
command = "zsh -lc 'exec yazi'"
description = "yazi file manager"
width = "92%"
height = "92%"

[[keys.command]]
key = "prefix+i"
type = "popup"
command = "zsh -lc 'exec gh dash'"
description = "GitHub PRs and issues"
width = "92%"
height = "92%"

[[keys.command]]
key = "prefix+t"
type = "popup"
command = "zsh -lc 'exec btop'"
description = "btop"
width = "85%"
height = "85%"

[ui]
status_indicators = "symbols"
prompt_new_tab_name = false

[ui.toast]
# macOS notifications when an agent in another tab finishes or needs you.
# "system" posts through terminal-notifier (clicking focuses Ghostty). Not
# "terminal": Ghostty drops those banners whenever its window is focused, and
# herdr lives in that window.
delivery = "system"
delay_seconds = 2

[session]
resume_agents_on_restore = true

[worktrees]
directory = "~/.herdr/worktrees"
EOF
  say "Validating:"
  if herdr config check; then
    ok "herdr config is valid"
    if [[ -n "${HERDR_ENV:-}" ]]; then run herdr server reload-config; fi
  else
    warn "herdr reported config problems (above)"
    SKIPPED+=("fix herdr config: herdr config check")
  fi
  pause
}

stage_agents() {
  say "For each agent, herdr can install:"
  step "a hook, so herdr can resume the exact conversation after a reboot or server restart"
  step "a skill (Claude), so the agent can drive herdr itself: start the dev server in a"
  step "side pane, wait for tests, open a helper agent next to it"
  printf '\n'
  say "Claude Code"
  if herdr_integration_current claude; then
    ok "herdr hook installed and current"
  elif confirm "Install herdr's Claude Code hook? (~/.claude/settings.json is backed up first)"; then
    backup "$HOME/.claude/settings.json"
    run herdr integration install claude
    CHANGED+=("$HOME/.claude/settings.json")
  else
    SKIPPED+=("herdr Claude hook: herdr integration install claude")
  fi
  local skill
  if skill=$(herdr --skill 2>/dev/null) && [[ -n "$skill" ]]; then
    install_file "$HOME/.claude/skills/herdr/SKILL.md" <<<"$skill"
  else
    warn "couldn't print herdr's skill file"
    SKIPPED+=("herdr skill: npx skills add herdrdev/herdr --skill herdr -g")
  fi
  printf '\n'
  say "Codex"
  if ! command -v codex >/dev/null 2>&1; then
    note "Codex isn't installed. Optional: brew install --cask codex, then: bash $SCRIPT_PATH --from 15"
  elif herdr_integration_current codex; then
    ok "herdr hook installed and current"
  elif confirm "Install herdr's Codex hook? (~/.codex config files are backed up first)"; then
    backup "$HOME/.codex/config.toml"
    backup "$HOME/.codex/hooks.json"
    run herdr integration install codex
  else
    SKIPPED+=("herdr Codex hook: herdr integration install codex")
  fi
  note "Agent sessions that are already running need a restart to pick these up."
  pause
}

stage_ghostty_herdr() {
  say "Every new Ghostty window (launch, Dock click, Cmd-N, quick terminal) follows one rule:"
  note "  herdr not open in any window   → the window attaches herdr"
  note "  herdr already open elsewhere   → plain shell. So Cmd-N is your 'without herdr' shortcut"
  note "  detach herdr with prefix q     → the window stays open as a plain shell; type herdr to go back"
  printf '\n'
  note "Why the old setup needed typing 'herdr': closing a Mac app's last window doesn't quit"
  note "the app, and Ghostty's initial-command only covered the first window after launch."
  printf '\n'
  write_ghostty_config
  step "Press Cmd-Shift-, (comma) to reload Ghostty's config."
  step "Try it: press Cmd-N. With herdr open here, the new window is a plain shell. Cmd-W closes it."
  note "Later, close every Ghostty window and click the Dock icon: it opens straight into herdr."
  pause
}

stage_permissions() {
  say "Notifications, so an agent in another tab or repo pings you when it finishes or needs you."
  note "herdr posts them through terminal-notifier, so they show even while Ghostty is in front."
  note "It stays quiet about the tab you're already looking at."
  printf '\n'
  if ! command -v terminal-notifier >/dev/null 2>&1; then
    brew_formulae terminal-notifier
  fi
  # The same call herdr makes: title, message, and focus Ghostty on click.
  cmd "terminal-notifier -title herdr -message 'Notifications are working' -activate com.mitchellh.ghostty"
  terminal-notifier -title "herdr" -message "Notifications are working" \
    -activate com.mitchellh.ghostty >/dev/null 2>&1 || warn "terminal-notifier failed to run"
  step "A banner saying 'Notifications are working' should appear top right."
  step "If macOS asks whether terminal-notifier may send notifications, click Allow."
  if ! confirm "Did the banner appear?"; then
    open_url "x-apple.systempreferences:com.apple.Notifications-Settings.extension"
    step "Find terminal-notifier in the list, turn on 'Allow notifications', pick Banners (or"
    step "Alerts to keep them on screen until dismissed). Check Focus / Do Not Disturb is off."
    pause "Press Enter when done"
    terminal-notifier -title "herdr" -message "Second try" -activate com.mitchellh.ghostty >/dev/null 2>&1 || true
    if ! confirm "Did this second banner appear?"; then
      SKIPPED+=("notifications: allow terminal-notifier in System Settings → Notifications")
    fi
  fi
  if [[ -n "${HERDR_ENV:-}" ]]; then
    printf '\n'
    say "Your current herdr window started before this fix, so it can't find terminal-notifier yet."
    step "After the wizard: press Ctrl-Space q (detach), then type  herdr  and Enter."
    note "Everything keeps running while you do that. New Ghostty windows get the fix automatically."
  fi
  printf '\n'
  say "Quick terminal: a drop-down terminal on Ctrl-\` from any app."
  step "Switch to another app (e.g. your browser) and press Ctrl-\` (the key left of 1)."
  step "If macOS asks for Accessibility access, click Open System Settings."
  if confirm "Open the Accessibility settings now?"; then
    open_url "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility"
    step "Turn Ghostty on (use + to add it from /Applications if missing)."
  fi
  note "If Ctrl-\` does nothing yet, it starts working after the next Ghostty launch."
  pause "Press Enter when done"
}

stage_statusline() {
  if ! command -v claude >/dev/null 2>&1; then
    note "Claude Code isn't installed, so there's nothing to configure. Skipping."
    pause
    return 0
  fi
  say "Optional: a two-line status bar under the prompt in every Claude Code session."
  say "Preview with sample data:"
  printf '\n'
  local preview sample
  preview=$(mktemp)
  statusline_script > "$preview"
  sample="{\"model\":{\"display_name\":\"Opus 5\"},\"workspace\":{\"current_dir\":\"$(current_projects_dir)/my-app\"},\"cost\":{\"total_cost_usd\":1.27},\"context_window\":{\"used_percentage\":38,\"total_input_tokens\":76000,\"context_window_size\":200000},\"effort\":{\"level\":\"high\"},\"rate_limits\":{\"five_hour\":{\"used_percentage\":23,\"resets_at\":$(( $(date +%s) + 7200 ))},\"seven_day\":{\"used_percentage\":61}}}"
  bash "$preview" <<<"$sample" | sed 's/^/    /'
  rm -f "$preview"
  printf '\n'
  note "context   % of the context window used, then tokens in context / window size"
  note "\$…       estimated cost of this session so far (resets on /clear)"
  note "5h / week % of your plan's rate limits (Pro/Max only), with the 5-hour reset time"
  note "Percentages go yellow at 50% and red at 80%. A worktree segment appears inside git worktrees."
  note "Claude Code doesn't report a running token total, so tokens shown are what's in context now."
  printf '\n'
  if statusline_configured; then
    ok "already set up in ~/.claude/settings.json"
  elif ! confirm "Set up this status line?"; then
    note "Skipped. Add it later with: bash $SCRIPT_PATH --from 18"
    pause
    return 0
  fi
  brew_formulae jq
  install_file "$STATUSLINE" < <(statusline_script)
  chmod +x "$STATUSLINE"
  local settings="$HOME/.claude/settings.json" tmp
  [[ -f "$settings" ]] || printf '{}\n' > "$settings"
  tmp=$(mktemp)
  if jq --arg cmd "$STATUSLINE" '.statusLine = {type: "command", command: $cmd, padding: 0}' "$settings" > "$tmp"; then
    install_file "$settings" < "$tmp"
  else
    warn "couldn't update $settings (is it valid JSON?)"
    SKIPPED+=("add statusLine to ~/.claude/settings.json by hand")
  fi
  rm -f "$tmp"
  note "Running Claude sessions pick it up on their next update; new sessions show it right away."
  pause
}

# ── Tour ──────────────────────────────────────────────────────────────────

stage_tour_launch() {
  if [[ -z "${HERDR_ENV:-}" ]]; then
    say "The tour runs inside herdr, so it survives closing Ghostty (you'll try that in step 8)."
    printf 'bash %q --tour' "$SCRIPT_PATH" | pbcopy
    step "Go to your herdr window. No herdr window? Close all Ghostty windows, then click"
    step "Ghostty in the Dock: it opens straight into herdr."
    step "Press Ctrl-Space c for a new tab, then Cmd-V and Enter (the command is on your clipboard):"
    note "bash $SCRIPT_PATH --tour"
    exit 0
  fi
  say "You're inside herdr. The wizard lives in this tab and keeps running whatever you close."
  step "Name this tab: prefix Shift-T (Ctrl-Space, then Shift-T), type 'tour', Enter."
  note "Coming back here at any point: prefix g (Cmd-P), pick the 'tour' tab."
  printf '\n'
  say "One workspace per repo:"
  step "prefix m (Cmd-O), type part of a repo name, Enter. A workspace for it appears in the sidebar."
  step "Do the same for two more repos. The tour calls them repo A, B and C."
  printf '\n'
  say "Switch between repos:"
  step "prefix ,  /  prefix .   (Cmd-Shift-[ / Cmd-Shift-]): previous / next workspace"
  step "prefix w: workspace list, arrows and Enter. Or click a name in the sidebar."
  step "prefix Shift-W renames a workspace. prefix Shift-D closes one (it asks first)."
  note "Each workspace keeps its own tabs, panes, running processes and directories."
  pause "Press Enter for step 2 of 9"
}

stage_tour_navigation() {
  say "Everything nests: Ghostty window › workspace (a repo) › tab › pane › popup."
  printf '\n'
  note "  Workspace  prefix m open repo · prefix , / . prev/next · prefix w list"
  note "  Tab        prefix c (Cmd-T) new · Cmd-1…9 jump · prefix n / p next/prev · prefix Shift-T rename"
  note "  Pane       Cmd-D right · Cmd-Shift-D down · prefix h j k l move · prefix z zoom · prefix x close"
  note "  Agent      prefix a / A next/previous agent · prefix o latest notification"
  note "  Anything   prefix g (Cmd-P) goto picker · prefix Space back to the last pane"
  note "  Popups     prefix d lazygit · f yazi · i GitHub PRs · t btop   (q closes)"
  note "  Mouse      click sidebar rows, tabs and panes; drag borders to resize"
  note "  Stuck?     prefix ? lists every key · run 'keys' for the cheat sheet"
  printf '\n'
  say "Drill (about a minute):"
  step "prefix . to jump to repo A. Cmd-D twice: three panes."
  step "prefix h / prefix l to hop between them, prefix z to zoom one and again to unzoom."
  step "prefix x on two panes to get back to one."
  step "prefix d: lazygit pops up over the pane. q closes it."
  step "prefix g, pick 'tour' to come back."
  pause "Press Enter for step 3 of 9"
}

stage_tour_agents() {
  say "Agents are ordinary programs in panes. herdr reads each one's state and shows it"
  say "in the sidebar: working, waiting for you, or idle."
  printf '\n'
  step "In repo A: run  claude"
  if command -v codex >/dev/null 2>&1; then
    step "In repo B: run claude, then Cmd-D and run  codex  in the right pane."
  else
    step "In repo B: run  claude"
  fi
  step "Ask repo B's Claude: 'run git status and summarise it'. Don't approve the prompt yet."
  step "Come back here (prefix g → tour). The sidebar marks that agent as waiting, and a macOS"
  step "banner appears. Clicking it brings Ghostty forward. (No banner for the tab you're looking at.)"
  step "prefix a jumps to the next agent (prefix A goes back). Approve the prompt."
  step "prefix o jumps to whatever the latest notification is about."
  printf '\n'
  say "Two agents on one repo without clashing:"
  step "Select repo A in the sidebar, press prefix Shift-G, give a branch name. herdr creates a"
  step "worktree workspace (under ~/.herdr/worktrees). Run a second claude there."
  printf '\n'
  note "Agents can drive herdr too. Ask Claude: 'start the dev server in a herdr pane next to you"
  note "and tell me when it is ready'."
  pause "Press Enter for step 4 of 9"
}

stage_tour_tabs() {
  say "Inside one repo, give each kind of work its own tab so every view stays put:"
  printf '\n'
  note "  1 agents   Claude / Codex sessions"
  note "  2 code     nvim (with an agent beside it, next step)"
  note "  3 dev      dev server │ test watcher"
  note "  4 review   gds, lazygit, git log"
  printf '\n'
  step "In repo A: prefix Shift-T, rename the tab with Claude in it to 'agents'."
  step "Cmd-T for a new tab, prefix Shift-T to name it 'code', run:  v ."
  step "Cmd-T again, name it 'dev', start the dev server (e.g. npm run dev). Cmd-D and run the"
  step "tests in watch mode on the right."
  step "Cmd-1 / Cmd-2 / Cmd-3 jump between tabs. prefix n / p cycles through them."
  printf '\n'
  note "New tabs and splits open in the directory of the pane you're in."
  note "Keep the same tab order in every repo, and Cmd-1…4 mean the same thing everywhere."
  note "The dev server keeps running when you switch repos, detach, or close Ghostty."
  pause "Press Enter for step 5 of 9"
}

stage_tour_nvim() {
  say "Recommended layout for coding with an agent: editor and agent side by side."
  printf '\n'
  note "  ┌─────────── nvim (60%) ───────────┬──── claude (40%) ────┐"
  note "  │ read code, review diffs, fix up  │ prompts, plans, runs │"
  note "  └──────────────────────────────────┴──────────────────────┘"
  printf '\n'
  step "In repo A's 'code' tab (nvim open): Cmd-D, run  claude  in the right pane."
  step "Drag the border so nvim gets about 60%."
  step "prefix Space flips between nvim and Claude. prefix z zooms whichever you're in."
  printf '\n'
  say "Set up in nvim for exactly this:"
  note "  files Claude edits reload by themselves within a second, no :e! needed"
  note "  ]h / [h jump between changed hunks · Space g h p previews a hunk inline"
  note "  Space g v reviews all uncommitted changes (Diffview) · Space g V closes it"
  note "  Space g g opens lazygit inside nvim · Space g s lists changed files"
  printf '\n'
  step "Long prompt? In Claude press Ctrl-G: it opens in nvim. :wq puts the text back in the prompt."
  note "Point Claude at code with @path (e.g. @src/app/page.tsx) instead of pasting it."
  pause "Press Enter for step 6 of 9"
}

stage_tour_review() {
  say "Let Claude change one file, then review it before anything gets committed."
  printf '\n'
  step "In repo A's Claude (code tab): 'Add a one-line comment at the top of README.md saying"
  step "what this repo is'. Approve the edit."
  step "In nvim: Space Space, open README.md. It updates on its own; the gutter marks the change."
  printf '\n'
  say "Pick a review style:"
  step "Terminal: in any pane run  gd  (inline, n jumps files) or  gds  (side by side). q quits."
  step "Structural: git dft ignores formatting noise and shows what actually changed."
  step "Neovim: Space g v. Changed files left, before/after right. Space g V closes."
  step "lazygit: prefix d. Enter on the file, space stages a line or hunk, | swaps delta and difftastic."
  printf '\n'
  step "Clean up: in lazygit select README.md and press d to discard the change."
  note "Habit: review every agent change like this before you commit, and commit in small steps."
  pause "Press Enter for step 7 of 9"
}

stage_tour_statusline() {
  if ! statusline_configured; then
    note "No status line set up, so there's nothing to show here."
    note "Add it any time: bash $SCRIPT_PATH --from 18"
    pause "Press Enter for step 8 of 9"
    return 0
  fi
  say "Look under the prompt in any Claude pane (it fills in after the first reply):"
  printf '\n'
  note "  line 1   model · effort level │ directory │ worktree (only inside a worktree)"
  note "  line 2   context % (tokens in context / window) │ session cost │ 5h limit + reset time │ week limit"
  note "  colours  percentages go yellow at 50% and red at 80%"
  printf '\n'
  step "Type /effort and pick a different level: the effort label changes."
  step "Type /model and switch: the model name (and maybe the window size) changes."
  step "Open Claude in the worktree workspace from step 3: the worktree segment appears."
  printf '\n'
  note "Context going yellow? /compact summarises the conversation and frees space."
  note "Starting something unrelated? /clear starts fresh (session cost goes back to \$0)."
  note "Near a limit on a heavy day? Lower /effort for routine work."
  pause "Press Enter for step 8 of 9"
}

stage_tour_resume() {
  say "herdr keeps everything in a background server, so closing is safe at every level:"
  printf '\n'
  step "One agent: /exit in Claude. The pane stays a shell. Later in that pane or repo:"
  step "  claude --continue (latest conversation) or claude --resume (pick one)."
  step "One pane: prefix x. One repo: prefix Shift-D on its workspace. Reopen it with prefix m,"
  step "  then claude --resume."
  step "Ghostty itself: Cmd-Q. Agents, dev servers and this tour keep running."
  step "  Click Ghostty in the Dock: herdr reattaches exactly where you were. Try it now."
  printf '\n'
  say "After a reboot, or 'herdr server stop':"
  note "  herdr restores workspaces, tabs, panes and directories, and resumes Claude and Codex"
  note "  conversations. Other processes (dev servers, watchers) restart as plain shells: re-run them."
  printf '\n'
  note "A plain shell without herdr: Cmd-N while herdr is open, or prefix q to detach this window."
  pause "Press Enter for step 9 of 9"
}

stage_tour_habits() {
  say "Habits that make this setup pay off:"
  printf '\n'
  note "• One workspace per repo, same tab order everywhere (agents, code, dev, review)."
  note "• Parallel work on one repo: one worktree per agent (prefix Shift-G). Merge via lazygit or a PR."
  note "• Let agents own their terminals: ask Claude to run the dev server or tests in a herdr pane."
  note "• Don't watch agents work. Notifications and prefix a bring you back when one needs you."
  note "• Review before every commit (Space g v or gds). Small commits make agent work easy to undo."
  note "• Name sessions with /rename so claude --resume is readable. /clear between unrelated tasks."
  note "• Watch the status line: /compact before context goes red; mind the 5h and week limits."
  note "• One-off command? Ctrl-\` from any app gives a plain shell without touching your layout."
  note "• Copy agent output: prefix e opens a pane's scrollback in nvim, prefix [ for copy mode."
  note "• Weekly: brew upgrade, then 'herdr integration status' to confirm the agent hooks are current."
  printf '\n'
  step "Run  keys  in any shell for the cheat sheet."
  step "Replay this tour any time: bash $SCRIPT_PATH --tour"
  pause "Press Enter to finish"
}

cheatsheet() {
  cat <<'EOF'
# Ghostty + herdr cheat sheet

Open any time with `keys`. **prefix** = Ctrl-Space: press, release, then the key.

## Windows

| Keys | Action |
|---|---|
| open Ghostty / Dock click | lands in herdr (if no other window shows herdr) |
| Cmd-N while herdr is open | plain shell window |
| prefix `q` | detach: this window becomes a plain shell, everything keeps running |
| `herdr` | attach again |
| Ctrl-\` | quick terminal from any app |

## Workspaces and agents

| Keys | Action |
|---|---|
| prefix `m` · Cmd-O | open a project as a new workspace |
| prefix `,` / `.` · Cmd-Shift-[ / ] | previous / next workspace |
| prefix `w` | workspace list |
| prefix `g` · Cmd-P | goto picker: any workspace, tab or agent |
| prefix `a` / `A` | next / previous agent (find the one waiting for you) |
| prefix `o` | jump to the latest notification |
| prefix `Shift-G` | new git worktree: a second agent on the same repo, own branch |
| prefix `Shift-W` / `Shift-D` | rename / close workspace |
| prefix `?` | every keybinding |

## Tabs and panes

| Keys | Action |
|---|---|
| prefix `c` · Cmd-T | new tab |
| prefix `1..9` · Cmd-1..9 | switch tab |
| prefix `n` / `p` | next / previous tab |
| prefix `Shift-T` | rename tab |
| prefix `v` · Cmd-D | split right |
| prefix `-` · Cmd-Shift-D | split down |
| prefix `h j k l` | move between panes |
| prefix `Space` | back to the last pane |
| prefix `z` · Cmd-Shift-Enter | zoom pane |
| prefix `x` | close pane |
| prefix `e` | open the pane's scrollback in nvim |
| prefix `[` | copy mode: `v` select, `y` copy, `/` search |
| prefix `b` | toggle sidebar |

## Popups

| Keys | Opens |
|---|---|
| prefix `d` · Cmd-Shift-G | lazygit |
| prefix `f` · Cmd-E | yazi |
| prefix `i` | gh dash (PRs, issues) |
| prefix `t` | btop |

## Claude Code

| Command | Does |
|---|---|
| `claude --continue` / `--resume` | resume the latest / pick a conversation |
| Ctrl-G | write the prompt in nvim |
| `@path/to/file` | point Claude at a file |
| `/rename`, `/clear`, `/compact` | name session, start fresh, free context |
| `/effort`, `/model` | change reasoning effort / model |

## Shell

| Command | Does |
|---|---|
| `p` | fuzzy-jump into a project |
| `y` | yazi; shell follows you to where you quit |
| `z <dir>` | jump to a frequent directory |
| Ctrl-R / Ctrl-T / Alt-C | fuzzy history / insert file / cd |
| `ll`, `lt` | list with git status / tree |
| `v`, `lg` | nvim / lazygit |
| `gd`, `gds` | git diff / side by side |
| `git dft`, `git dlog` | structural diff / log with difftastic |
| `jless file.json` | fold and explore JSON |
| `tldr <cmd>` | quick examples |

## Diffs (delta)

`n` / `N` next / previous file · `q` quit

## lazygit

`space` stage · `enter` on a file to stage single lines · `c` commit · `P` push · `p` pull · `d` discard · `|` delta ↔ difftastic · `?` help

## Neovim (LazyVim)

`Space` menu · `Space Space` find file · `Space /` grep · `Space e` file tree · `gd` definition · `gr` references · `K` hover · `Space ca` code action · `Space cf` format

Reviewing agent changes: `]h` / `[h` next / previous hunk · `Space ghp` preview hunk · `Space gv` Diffview review · `Space gV` close · `Space gs` changed files · `Space gg` lazygit

## Ghostty

Ctrl-\` quick terminal · Cmd-N plain shell (when herdr is open) · Cmd-Shift-, reload config
EOF
}

# ── Runner ────────────────────────────────────────────────────────────────

STAGES=(
  "stage_preflight:Preflight"
  "stage_install_ghostty:Install Ghostty and JetBrains Mono Nerd Font"
  "stage_ghostty_config:Ghostty config"
  "stage_move_into_ghostty:Move into Ghostty"
  "stage_free_ctrl_space:Free up Ctrl-Space for herdr"
  "stage_toolbelt:CLI toolbelt"
  "stage_starship:Starship prompt (pastel powerline)"
  "stage_shell:Shell: history search, aliases, project jumper"
  "stage_git_diffs:Git diffs: delta and difftastic"
  "stage_lazygit:lazygit"
  "stage_github:GitHub CLI and gh-dash"
  "stage_neovim:Neovim + LazyVim"
  "stage_yazi:yazi file manager"
  "stage_herdr:herdr"
  "stage_agents:Connect herdr to Claude Code and Codex"
  "stage_ghostty_herdr:Ghostty: open herdr automatically"
  "stage_permissions:macOS permissions: notifications and quick terminal"
  "stage_statusline:Claude Code status line (optional)"
  "stage_tour_launch:Tour 1/9 · Land in herdr, one workspace per repo"
  "stage_tour_navigation:Tour 2/9 · Moving around"
  "stage_tour_agents:Tour 3/9 · Run and juggle agents"
  "stage_tour_tabs:Tour 4/9 · Tabs inside one repo"
  "stage_tour_nvim:Tour 5/9 · Neovim next to your agent"
  "stage_tour_review:Tour 6/9 · Claude edits, you review"
  "stage_tour_statusline:Tour 7/9 · Reading the status line"
  "stage_tour_resume:Tour 8/9 · Close anything, pick up later"
  "stage_tour_habits:Tour 9/9 · Daily habits"
)
TOTAL_STAGES=${#STAGES[@]}
TOUR_START=19

usage() {
  cat <<EOF
usage: bash $(basename "$0") [--from N | --only N,N | --skip N,N | --tour | --list]

  (no flags)  run every stage; finished stages report "already done" and move on
  --from N    start at stage N (see --list)
  --only N,N  run just these stages, e.g. --only 14,16,17
  --skip N,N  run everything except these stages, e.g. --skip 11,13 (no GitHub, no yazi)
  --tour      only the guided tour (stages $TOUR_START-$TOTAL_STAGES)
  --list      print the stages and exit
EOF
}

FROM=1
ONLY=""
SKIP=""
case "${1:-}" in
  "") ;;
  --tour) FROM=$TOUR_START ;;
  --from)
    FROM="${2:-}"
    if ! [[ "$FROM" =~ ^[0-9]+$ ]] || (( FROM < 1 || FROM > TOTAL_STAGES )); then
      usage
      exit 2
    fi
    ;;
  --only)
    ONLY=",${2:-},"
    if ! [[ "$ONLY" =~ ^,[0-9]+(,[0-9]+)*,$ ]]; then
      usage
      exit 2
    fi
    ;;
  --skip)
    SKIP=",${2:-},"
    if ! [[ "$SKIP" =~ ^,[0-9]+(,[0-9]+)*,$ ]]; then
      usage
      exit 2
    fi
    ;;
  --list)
    i=0
    for entry in "${STAGES[@]}"; do
      i=$((i + 1))
      printf '%3d  %s\n' "$i" "${entry#*:}"
    done
    exit 0
    ;;
  -h | --help) usage; exit 0 ;;
  *) usage; exit 2 ;;
esac

banner "Ghostty + herdr terminal for coding agents"
for entry in "${STAGES[@]}"; do
  if (( _STAGE_INDEX + 1 < FROM )) ||
    [[ -n "$ONLY" && "$ONLY" != *",$((_STAGE_INDEX + 1)),"* ]] ||
    [[ "$SKIP" == *",$((_STAGE_INDEX + 1)),"* ]]; then
    _STAGE_INDEX=$((_STAGE_INDEX + 1))
    continue
  fi
  stage "${entry#*:}"
  "${entry%%:*}"
done

finish
if (( ${#CHANGED[@]} )); then
  note "files created or changed:"
  for f in "${CHANGED[@]}"; do note "  - $f"; done
fi
if [[ -d "$BACKUP_DIR" ]]; then
  note "backups of what was there before: $BACKUP_DIR"
fi
printf '\n  Run %skeys%s for the cheat sheet. Replay the tour: bash %s --tour\n\n' "$BOLD" "$RESET" "$SCRIPT_PATH"
